if(NOT TARGET options::modern-cpp)
  if(TARGET options::cpp17)
    add_library(options::modern-cpp INTERFACE IMPORTED GLOBAL)
    target_link_libraries(options::modern-cpp INTERFACE options::cpp17)
  elseif(TARGET options::cpp14)
    add_library(options::modern-cpp INTERFACE IMPORTED GLOBAL)
    target_link_libraries(options::modern-cpp INTERFACE options::cpp14)
  elseif(TARGET options::cpp11)
    add_library(options::modern-cpp INTERFACE IMPORTED GLOBAL)
    target_link_libraries(options::modern-cpp INTERFACE options::cpp11)
  else()
    message(FATAL_ERROR "options::modern-cpp expects options::cpp11 or above.")
  endif()
endif()
